service: template-lambda-nestjs

plugins:
  - serverless-offline
  - serverless-jetpack

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  environment:
    DATABASE_HOST: ${env:DATABASE_HOST}
    DATABASE_USERNAME: ${env:DATABASE_USERNAME}
    DATABASE_PASSWORD: ${env:DATABASE_PASSWORD}
    DATABASE_NAME: ${env:DATABASE_NAME}
    DATABASE_PORT: ${env:DATABASE_PORT}


functions:
  main:
    handler: dist/lambda.handler
    events:
      - http:
          method: any
          path: /{any+}
